### ISSUE TITLE
Serving bootstrap over HTTPS

### ISSUE THREAD

**Issue by igorkulman** [jsonresume/jsonresume-theme-modern#9]
This theme server `http://bootswatch.com/lumen/bootstrap.min.css` which breaks the template when served over HTTPS (like `https://registry.jsonresume.org/igorkulman`). Should be changed to `//bootswatch.com/lumen/bootstrap.min.css`

**Comment by skoenig** [comment]
`//bootswatch.com/lumen/bootstrap.min.css` returns a 404, perhaps it is better to use [BootstrapCDN](https://www.bootstrapcdn.com/) nowadays: `https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/lumen/bootstrap.min.css`.
